### ISSUE TITLE
Allow configuring weather stats

### ISSUE THREAD

**Issue by hoovercj** [hoovercj/strava-weather-reporter#42]
Allow users to configure which stats to show (i.e. checkboxes to toggle on/off summary, temperature, humidity, dew point, wind, etc.

**Comment by PedersenThomas** [comment]
I would also like to change the units, eg. `Temperature: 15° (60F)` since I care more about the metric system.

**Comment by hoovercj** [comment]
@PedersenThomas you can already do that.

In the top right corner there is a "settings" cog which opens a dialog with a few options (shown below).

I hope that helps!

![image](https://user-images.githubusercontent.com/2957173/45863853-3a801d80-bd78-11e8-839a-aba90e80068e.png)

**Comment by hoovercj** [comment]
This is checked in and has been working for a week. Closing as complete.
